In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

1) Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.

In [7]:
array1 = np.array([1, 3.2, 5, 7, 9.6, 11, 13.8, 15, 17, 19.1, 21],dtype = "int")
print(array1)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [11]:
array1 = np.array([1, 3.2, 5, 7, 9.6, 11, 13.8, 15, 17, 19.1, 21])

print(array1.ndim)  # .ndim : NumPy array'inin kaç boyuttan oluştuğunu belirtir.
                    # Bu, array'in yapısının derinliğini anlamamıza yardımcı olur.

1


In [12]:
print(array1.size)  # size : Array'da bulunan eleman sayısını verir.

11


2) İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

In [13]:
array2 = np.array([[9,8,7,5],[1,2,3,0]])
print(array2)

[[9 8 7 5]
 [1 2 3 0]]


In [23]:
array2 = np.array([[9,8,7,5],[1,2,3,0]])
print(array2.ndim)    # .ndim : NumPy array'inin kaç boyuttan oluştuğunu belirtir.

2


In [24]:
print(array2.size)    # size : Array'da bulunan eleman sayısını verir.

8


In [17]:
print(array2)
print(array2.shape)  # shape metodu, dizinin boyutlarını (satır ve sütun sayısını) döndürür.
                     # Burda 2 satır ve 4 sütundan oluşmuştur.

[[9 8 7 5]
 [1 2 3 0]]
(2, 4)


In [18]:
#2.satırdaki 3.elemana ulaşalım.
array2[1,2]

3

In [19]:
#1.satırdaki 4.elemana ulaşalım.
array2[0,3]

5

In [21]:
# 8,7,2,3 dilimleme yaparak bu sayıları yazdıralım.
array2[0:2,1:3]


array([[8, 7],
       [2, 3]])

In [22]:
#5,0 dilimleme yaparak bu sayıları yazdıralım.
array2[:,3]

array([5, 0])

In [32]:
# 3 Boyutlu Dizi (3-D Array)

array3 = np.array([[[5,3,7],[8,1,7]],
            [[4,5,6],[4,6,8]]])

print(array3)

[[[5 3 7]
  [8 1 7]]

 [[4 5 6]
  [4 6 8]]]


In [44]:
array3 = np.array([[[5,3,7],[8,1,7]],
            [[4,5,6],[4,6,8]]])

print(array3.ndim)    # .ndim : NumPy array'inin kaç boyuttan oluştuğunu belirtir.

3


In [45]:
print(array3.size)    # size : Array'da bulunan eleman sayısını verir.

12


In [46]:
print(array3)
print(array3.shape)   # shape metodu, dizinin boyutlarını (satır ve sütun sayısını) döndürür.

[[[5 3 7]
  [8 1 7]]

 [[4 5 6]
  [4 6 8]]]
(2, 2, 3)


In [36]:
#1.katmandaki 2.satırdaki 2. elemana ulaşalım.
array3[0,1,1]

1

In [37]:
#2.katmandaki 1.satırdaki 3. elemana ulaşalım.
array3[1,0,2]

6

In [42]:
# 6,8 sayılarını dilimleme yaparak yazdıralım.
array3[1,:,2:3]

array([[6],
       [8]])

In [43]:
# 3,1,5,6 sayılarını dilimleme yaparak yazdıralım.
array3[:,:,1:2]

array([[[3],
        [1]],

       [[5],
        [6]]])

3) Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

In [47]:
array4 =np.array([0,5,8,6,7,2])
print(array4)

[0 5 8 6 7 2]


In [48]:
array4[4]

7

In [49]:
array4[-1]

2

In [50]:
array4[1:3]

array([5, 8])

In [51]:
array4[3:]

array([6, 7, 2])

In [53]:
array5 = np.array([[3,8,0],[9,7,3],[4,6,2]])
print(array5)

[[3 8 0]
 [9 7 3]
 [4 6 2]]


In [54]:
# 2. satırdaki 3.elemana ulaşalım
array5[1,2]

3

In [55]:
# 3. satırdaki 1.elemana ulaşalım.
array5[2,0]

4

In [61]:
# 0,3,2 sayılarını dilimleme yaparak yazdıralım.
array5[0:3,2]

array([0, 3, 2])

In [66]:
# 9,4,7,6 sayılarını dilimleme yaparak yazdıralım.
array5[1:3,0:2]

array([[9, 7],
       [4, 6]])

In [67]:
array6 = np.array([[[1,9,3],[2,9,8]],
                   [[2,8,7],[1,0,5]]])
print(array6)

[[[1 9 3]
  [2 9 8]]

 [[2 8 7]
  [1 0 5]]]


In [68]:
#1. katmandaki 2.satırdaki 1. elemana ulaşalım.
array6[0,1,0]

2

In [69]:
#2.katmandaki 1.satırdaki 3.elemana ulaşalım.
array6[1,0,2]

7

In [70]:
#2,9,8 sayılarını dilimleme kullanarak yazdıralım.
array6[0,1,0:3]

array([2, 9, 8])

In [71]:
#3,8,7,5 sayılarını dilimleme kullanacak yazdıralım.
array6[:,:,2:3]

array([[[3],
        [8]],

       [[7],
        [5]]])

4) Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir. 

In [82]:
array7 = np.zeros((3,4),dtype = "int") #np.zeros():Belirtilen şekil ve boyutta sıfırlarla dolu bir NumPy dizisi oluşturur.
print(array7)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [83]:
array8 = np.ones((3,4),dtype = "int")  #np.ones():Belirtilen şekil ve boyutta birlerle dolu bir NumPy dizisi oluşturur.
print(array8)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [81]:
#Birleştirme (Concatenation) : Diziler belirli bir eksende birleştirilir.Bu dizilerin yan yana veya üst üste eklenmesini ifade eder.

np.concatenate([array7,array8],axis = 0)  #axis = 0 her satır boyunca yapılan işlemdir.

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [80]:
np.concatenate([array7,array8],axis = 1) #axis = 1 her sütün boyunca yapılan işlemdir.

array([[0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1]])